<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

/** @var AbstractBlock $sectionBlock */
/** @var Escaper $escaper */

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\AbstractBlock;

?>
<div class="flex pt-6 pb-3 mx-auto mb-6 md:flex-row">
    <h2 class="w-full text-2xl font-bold text-center text-gray-900 title-font md:text-left">
        <?= $sectionBlock->getTitle() ? $escaper->escapeHtml($sectionBlock->getTitle()) : '&nbsp;' ?>
    </h2>
</div>
