<?php

/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

/** @var AbstractBlock $sectionBlock */
/** @var Escaper $escaper */

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\AbstractBlock;

?>
<div x-data="{ open: false }" @click.away="open = false" class="relative">
    <h2 @click="open = !open" class="w-1/2 text-2xl font-bold text-center cursor-pointer text-giallo title-font md:text-left">
        <span x-show="!open">+</span>
        <span x-show="open">-</span>
        <?= $sectionBlock->getTitle() ? $escaper->escapeHtml($sectionBlock->getTitle()) : '&nbsp;' ?>
    </h2>