<?php

/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Shop By Brand Compatibility with Hyva for Magento 2
 */
/** @var HeroiconsOutline $heroicons */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Framework\Escaper;

/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

$heroicons = $viewModels->require(HeroiconsOutline::class);
// phpcs:disable Generic.Files.LineLength.TooLong
?>
<section class="my-12 text-gray-700 body-font"
     x-data="{...amMoreFromBrand(), ...amMoreFromBrandSlider(), autoplay: null}"
     @resize.window.debounce="calcPageSize(); $nextTick( function() { calcActive() })" 
     x-init="moreFromBrandsInit(); autoplay = setInterval(() => { if (!products || !products.length) { clearInterval(autoplay); } else if (active < products.length-pageSize) { getSlider().scrollLeft =
                            (getSlider().scrollWidth / (products.length + pageFillers)) * (active + pageSize);
                            active += pageSize } else { getSlider().scrollLeft = 0; active = 0;} }, 3000)">


    <template x-if="products && products.length">
        <div class="relative">
            <div class="container flex flex-col items-center pt-6 pb-3 mx-auto mb-6 border-b-2 border-gray-300 md:flex-row">
                <h3 class="text-2xl font-medium text-gray-900 title-font" x-html="title"></h3>
            </div>
            <div class="relative w-full overflow-x-hidden">
                <div class="relative flex w-full overflow-auto transition-all flex-nowrap js_slides snap" @scroll.debounce="calcActive">
                    <template x-for="product in products" :key="product.id">
                        <?= $block->getChildHtml('product_item') ?>
                    </template>
                    <div :class="{
                        'js_dummy_slide w-1/2 lg:w-1/3 xl:w-1/4 flex flex-shrink-0 py-1' : pageFillers > 0
                        }"></div>
                    <div :class="{
                        'js_dummy_slide w-1/2 lg:w-1/3 xl:w-1/4 flex flex-shrink-0 py-1' : pageFillers > 1
                        }"></div>
                    <div :class="{
                        'js_dummy_slide w-1/2 lg:w-1/3 xl:w-1/4 flex flex-shrink-0 py-1' : pageFillers > 2
                        }"></div>
                </div>
            </div>
            <div style="min-height: 65px">
                <template x-if="products.length && products.length > pageSize">
                    <div class="flex items-center justify-center flex-1 p-4" x-cloak>
                        <button aria-label="<?= $escaper->escapeHtmlAttr(__('Previous')) ?>" class="w-8 h-8 mx-4 text-black rounded-full outline-none focus:outline-none" :class="{ 'invisible' : active === 0 }" @click="getSlider().scrollLeft =
                                (getSlider().scrollWidth / (products.length + pageFillers)) * (active - pageSize);
                                active -= pageSize;">
                            <?= $heroicons->chevronLeftHtml("w-5 h-5", 25, 25) ?>
                        </button>
                        <template x-for="(product, index) in products" :key="index">
                            <span class="flex-shrink-0 block w-3 h-3 mx-1 bg-black bg-opacity-25 rounded-full shadow cursor-pointer" :class="{
                                        'bg-opacity-100': active === index,
                                        'hidden': (pageSize !== 1 && !!(index % pageSize))
                                        }" @click="getSlider().scrollLeft =
                                          (getSlider().scrollWidth / (products.length + pageFillers)) * index;
                                          active = index;">
                            </span>
                        </template>
                        <button aria-label="<?= $escaper->escapeHtmlAttr(__('Next')) ?>" class="w-8 h-8 mx-4 text-black rounded-full outline-none focus:outline-none" :class="{ 'invisible' : active >= products.length-pageSize }" @click="getSlider().scrollLeft =
                                (getSlider().scrollWidth / (products.length + pageFillers)) * (active + pageSize);
                                active += pageSize">
                            <?= $heroicons->chevronRightHtml("w-5 h-5", 25, 25) ?>
                        </button>
                    </div>
                </template>
            </div>
        </div>
    </template>
</section>

<?= $block->getChildHtml('more_from_brand_js') ?>