<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Shop By Hyva Compatibility
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Framework\Escaper;
use Magento\LayeredNavigation\Block\Navigation;
use Amasty\ShopbyHyvaCompatibility\ViewModel\JsInit;

// phpcs:disable Generic.Files.LineLength.TooLong

/** @var Navigation $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var JsInit $jsInitViewModel */
$jsInitViewModel = $viewModels->require(JsInit::class);

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

$isSidebar = $block->getData('isSidebar');
?>
<?php if ($block->canShowBlock()): ?>
    <div class="block-filter flex flex-col<?= $isSidebar ? ' md:block' : '-top hidden md:block' ?> border border-container p-4 md:border-0 md:py-0 md:px-0"
        <?php if ($isSidebar): ?>
         x-data="initLayeredNavigation()"
         x-init="checkIsMobileResolution($el)"
         @resize.window.debounce="checkIsMobileResolution($el)"
         @visibilitychange.window.debounce="checkIsMobileResolution($el)"
        <?php else: ?>
         id="layered-filter-block"
        <?php endif; ?>
    >
        <div class="flex items-center justify-between h-10 block-title lg:hidden"
            <?php if ($isSidebar): ?>
             :class="{'mb-4' : isApplySticy }"
             @click="blockOpen = !blockOpen"
            <?php endif; ?>
        >
            <span class="text-xl font-semibold uppercase text-primary text-md md:text-2xl lg:hidden">
                <?= $escaper->escapeHtml(__('Shop By')) ?>
            </span>
            <span class="hidden px-1 py-1 border rounded border-container-darker"
                <?php if ($isSidebar): ?>:class="{ 'block' : isMobile, 'hidden': !isMobile }"<?php endif; ?>>
                <?php if ($isSidebar): ?>
                    <?= $heroicons->chevronDownHtml(
                        'transition-transform transform duration-300 ease-in-out',
                        24,
                        24,
                        [":class" => "{ 'rotate-180': blockOpen }"]
                    ); ?>
                <?php endif; ?>
            </span>
        </div>
        <?= $block->getChildHtml('state') ?>
        <div class="hidden lg:shadow-2xl block-content filter-content md:block lg:rounded-b-4" <?php if ($isSidebar): ?>id="layered-filter-block-content" :class="{ 'hidden' : isMobile && !blockOpen, '' : isApplySticy }"<?php endif; ?>>
            <?php foreach ($block->getFilters() as $filter): ?>
                <?php if ($filter->getItemsCount()): ?>
                    <div class="relative border-b-0 lg:first-of-type:border-t-4 lg:first-of-type:rounded-t-xl filter-option card border-primary border-x-0" x-data="{ open: false }" @filter-open-state="open = true">
                        <div
                            class="flex items-center justify-start cursor-pointer filter-options-title hover:text-secondary-darker border-container"
                            :class="{ 'border-b pb-4': open }"
                            @click="open = !open">
                            <span class="font-semibold title text-md md:text-lg">
                                <?= $escaper->escapeHtml(__($filter->getName())) ?>
                                </span>
                            <span class="order-2 px-1 py-1 ml-auto border rounded border-container">
                                <?= $heroicons->chevronDownHtml(
                                    'transition-transform transform duration-300 ease-in-out',
                                    24,
                                    24,
                                    [":class" => "{ 'rotate-180': open }"]
                                ); ?>
                            </span>
                        </div>
                        <div class="pt-3 filter-options-content" x-show="open" x-cloak>
                            <?= /* @noEscape */ $block->getChildBlock('renderer')->render($filter) ?>
                        </div>
                    </div>
                <?php endif; ?>
            <?php endforeach; ?>
        </div>
    </div>
    <?php if ($isSidebar): ?>
        <script>
            function initLayeredNavigation() {
                return {
                    selectors: {
                        sidebar: '.sidebar-main',
                        filterContent: '.filter-content',
                        columns: '.columns',
                        body: '#html-body',
                        filterItem: '.am-filter',
                        filterOption: '.filter-option',
                        selectedClass: '.amshopby-link-selected'
                    },
                    filtersOverflowOffset: 25,
                    isMobile: false,
                    blockOpen: false,
                    isStickyEnabled: Boolean(<?= /** @noEscape  */ $jsInitViewModel->getEnableStickySidebarDesktop(); ?>),
                    isApplySticy: false,

                    checkIsMobileResolution(element) {
                        this.isMobile = window.matchMedia('(max-width: 768px)').matches;

                        this.$nextTick(() => {
                            if (this.isStickyEnabled && !this.isMobile) {
                                this.isApplySticy = true;

                                this.enableStikySidebar(element);
                            }
                            this.openFiltersByDefault(element);
                        })
                    },
                    enableStikySidebar(element) {
                        const bodyElement = document.querySelector(this.selectors.body);
                        const filtersBlock = document.querySelector(this.selectors.filterContent);
                        const filtersMaxHeight = element.offsetHeight - filtersBlock.offsetHeight + this.filtersOverflowOffset;

                        // add classes
                        bodyElement.classList.add('-amshopby-sticky');
                        element.classList.add('-amshopby-sticky');
                        // set container max-height
                        filtersBlock.style.maxHeight = 'calc(100vh - ' + filtersMaxHeight + 'px)'
                    },

                    openFiltersByDefault(element) {
                        let filters = element.querySelectorAll(this.selectors.filterItem);
                        filters.forEach((filter) => {
                            let filterOPtion = filter.closest(this.selectors.filterOption);
                            let hasSelectedOption = filter.querySelector(this.selectors.selectedClass);
                            switch (parseInt(filter.dataset.amshopbyExpanded)) {
                                case 1:
                                    this._openFilterEvent(filterOPtion);
                                    break;
                                case 2:
                                    if(!this.isMobile) {
                                        this._openFilterEvent(filterOPtion);
                                    }
                                    break;
                                default:
                                    if(hasSelectedOption) {
                                        this._openFilterEvent(filterOPtion);
                                    }
                            }
                        })
                    },

                    /**
                     * Create event for open filter
                     * @param target element for creating event
                     * @returns {*}
                     * @private
                     */
                    _openFilterEvent(target) {
                        return target.dispatchEvent(new CustomEvent('filter-open-state', {}));
                    }
                }
            }
        </script>
    <?php endif; ?>
<?php endif; ?>
