<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Customer\Block\Form\Login\Info;
use Magento\Framework\Escaper;

/** @var Info $block */
/** @var Escaper $escaper */
?>
<?php if ($block->getRegistration()->isAllowed()): ?>
    <div class="flex flex-col justify-center w-full py-16 lg:py-0 block-new-customer lg:w-1/2 md:my-0 bg-gradient-to-tr from-green-100 via-emerald-200 to-emerald-300">
        <div class="block-title">
        <?= $block->getBlockHtml('page.main.title') ?>
            <h1 class="mb-3 text-3xl font-bold text-center text-gray-600 title-font" role="heading"
                aria-level="2"><?= $escaper->escapeHtml(__('Welcome to login')) ?></h1>
        </div>
        <div class="mt-4 text-center block-content" aria-labelledby="block-new-customer-heading">
            <p>
                <?= $escaper->escapeHtml( // phpcs:disable Generic.Files.LineLength.TooLong
                    __('Do you have an account?')
                ) // phpcs:enable ?>
            </p>
        </div>
        <div class="flex justify-center pt-6 pb-2">
            <a href="<?= $escaper->escapeUrl($block->getCreateAccountUrl()) ?>"
               class="rounded-full btn bg-turchese hover:bg-turchese-600"><span><?= $escaper->escapeHtml(__('Sign Up')) ?></span></a>
        </div>
    </div>
<?php endif; ?>
