<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Checkout\Block\Cart\Coupon;
use Magento\Framework\Escaper;

/** @var Coupon $block */
/** @var Escaper $escaper */

// We should use strlen function because coupon code could be "0", converted to bool will lead to false
$hasCouponCode = (bool) strlen($block->getCouponCode() ?: "");
?>
<script>
    function initCouponForm() {
        return {
            showCouponForm: <?= $hasCouponCode ? 1 : 0 ?>,
            formData: {
                coupon_code: '<?= $escaper->escapeJs(
                    $block->getCouponCode()
                ) ?>',
                remove: '<?= (int) $hasCouponCode ?>'
            },
            init(){
                this.showCouponForm = JSON.parse(hyva.getBrowserStorage().getItem('hyva.showCouponForm'))
            },
            toggleShowCoupon(){
                this.showCouponForm = !this.showCouponForm;

                hyva.getBrowserStorage().setItem('hyva.showCouponForm', this.showCouponForm);

                this.$nextTick(() => this.$refs.couponInput.select());
            }
        }
    }
</script>
<div class="pt-6 coupon-form"
     x-data="initCouponForm()"
     x-init="init()"
>
    <form id="discount-coupon-form"
            class="flex w-1/2 p-4 my-4 bg-white rounded"
            x-cloak
            action="<?= $escaper->escapeUrl(
                $block->getUrl("checkout/cart/couponPost")
            ) ?>"
            method="post"
            @submit.prevent="hyva.postCart($event.target)"
    >
        <?= $block->getBlockHtml("formkey") ?>

        <div class="fieldset coupon">

            <input type="hidden" name="remove" id="remove-coupon" value="<?= (int) $hasCouponCode ?>"/>

            <div class="flex flex-row justify-start gap-2 mb-3 sm:mb-0">

                <label for="coupon_code" class="sr-only label">
                    <?= $escaper->escapeHtml(
                        __("Enter discount code")
                    ) ?>
                </label>
                <div class="control">
                    <input type="text"
                            class="w-full xl:w-[22rem] focus:ring-0 focus:border-gray-300 form-input disabled:opacity-75 disabled:bg-gray-100 disabled:pointer-events-none placeholder-gray-400 h-12"
                            id="coupon_code"
                            name="coupon_code"
                            value="<?= $escaper->escapeHtmlAttr(
                                $block->getCouponCode()) ?>"
                            x-model="formData.coupon_code"
                            x-ref="couponInput"
                            placeholder="<?= $escaper->escapeHtmlAttr(__("Enter discount code")) ?>"
                    />
                </div>

                <div>
                    <?php if (!$hasCouponCode): ?>
                    <div class="primary">
                        <button class="h-12 text-sm btn bg-rosso hover:bg-rosso-darker" type="submit" value="<?= $escaper->escapeHtmlAttr(
                            __("Apply Discount")
                        ) ?>">
                            <span><?= $escaper->escapeHtml(
                                __("Apply Discount")
                            ) ?></span>
                        </button>
                    </div>
                    <?php else: ?>
                        <div class="primary">
                            <button type="submit" class="btn btn-primary"
                                    value="<?= $escaper->escapeHtmlAttr(
                                        __("Cancel Coupon")
                                    ) ?>">
                                <?= $escaper->escapeHtml(
                                    __("Cancel Coupon")
                                ) ?>
                            </button>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </form>
</div>

