<?php

/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\SvgIcons;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var SvgIcons $hyvaicons */
$hyvaicons = $viewModels->require(SvgIcons::class);

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);
?>

<button type="submit" form="product_addtocart_form" title="<?= $escaper->escapeHtmlAttr(__('Add to cart')) ?>" class="items-center justify-center gap-2 text-lg uppercase btn bg-rosso hover:bg-rosso-400 hover:scale-105" id="product-addtocart-button">
<?= $hyvaicons->shoppingBagHtml('w-8 h-8'); ?>

        <span class="block"><?= $block->getData('is_cart_configure') ?
                                        $escaper->escapeHtml(__('Update item')) :
                                        $escaper->escapeHtml(__('Add to cart')) ?>
        </span>
</button>

<?= $block->getChildHtml('', true) ?>