<?php

/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\ProductAttributes;
use Hyva\Theme\ViewModel\ProductCompare;
use Hyva\Theme\ViewModel\ProductPage;
use Hyva\Theme\ViewModel\Wishlist;
use Magento\Catalog\Model\Product;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Hyva\Theme\ViewModel\SvgIcons;
use Hyva\Theme\ViewModel\HeroiconsOutline;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

/** @var SvgIcons $hyvaicons */
$hyvaicons = $viewModels->require(SvgIcons::class);

/** @var ProductPage $productViewModel */
$productViewModel = $viewModels->require(ProductPage::class);
/** @var ProductAttributes $attributesViewModel */
$attributesViewModel = $viewModels->require(ProductAttributes::class);
/** @var Product $product */
$product = $productViewModel->getProduct();

?>
<div class="order-2 w-full mb-6 md:pl-5 lg:pl-10 md:pb-0 lg:w-1/2 xl:w-1/2 md:mb-0">
    <?php  ?>
    <h1 class="hidden my-1 text-xl text-primary md:block md:text-3xl title-font">
        <strong class="font-semibold md:font-bold"><?= $escaper->escapeHtml($product->getName()) ?></strong>
    </h1>
    <?php if ($shortDescription = $productViewModel->getShortDescription()) { ?>
        <div class="pt-2 pb-0 leading-relaxed prose product-description"><?= /* @noEscape */ $shortDescription ?></div>
    <?php } ?>

    <div class="flex flex-row items-center justify-between w-full gap-4 mb-4 lg:items-center lg:justify-start lg:flex-row sm:w-4/5">
    <div class="flex mt-2">
    <span class="font-semibold text-gray-900 product-detail-value"><?= $escaper->escapeHtml(__('Brands:')) ?></span>
    <?php
    $brand = $product->getAttributeText('farmaregno_brand');
    if (is_array($brand)) {
        foreach ($brand as $index => $b) {
            if ($index == 1) {
                ?>
                <span class="font-semibold text-gray-900 ml-14 product-detail-value"><?= $escaper->escapeHtml(__('Line:')) ?></span>
                <?php
            }
            ?>
            <a class="px-2 ml-2 font-semibold text-primary hover:bg-primary hover:text-white border-primary focus:ring-0 btn shadow-none bg-white py-0 border rounded-lg product-detail-label <?php if (empty($b)) { echo 'hidden'; } ?>">
                <?= $escaper->escapeHtml($b) ?>
            </a>
            <?php
        }
    } else {
        ?>
        <a class="px-2 ml-2 font-semibold text-primary hover:bg-primary hover:text-white border-primary focus:ring-0 btn shadow-none bg-white py-0 border rounded-lg product-detail-label <?php if (empty($brand)) { echo 'hidden'; } ?>">
            <?= $escaper->escapeHtml($brand) ?>
        </a>
        <?php
    }
    ?>
</div>

    </div>

   


    <div class="flex flex-col items-center justify-between gap-4 mb-4 lg:items-start lg:gap-0 sm:flex-row">
        <?= $block->getChildHtml("alert.urls") ?>
        <?= $block->getChildHtml("product.info.stockstatus") ?>
        <a class="flex items-center justify-center gap-2 font-semibold text-primary-lighter" href="tel:390731081507">
                <?= $hyvaicons->cuffieHtml('w-4 h-4'); ?>
                <?= $escaper->escapeHtml(__('Talk to a pharmacist')) ?>
            </a>
    </div>


    <?= $block->getChildHtml('product.info.form') ?>

    <div class="flex flex-col items-end gap-6 py-4 border-t md:flex-row lg:flex-col xl:flex-row xl:gap-8">

        <div class="flex justify-center w-full gap-2 lg:justify-between lg:flex-row xl:flex-col md:w-1/3 lg:w-full xl:w-1/3">
            <?= $block->getChildHtml("product.info.price") ?>
        </div>

        <div class="flex flex-col w-full gap-2 md:w-2/3 lg:w-full xl:w-2/3">
            
            <?php if ($product->isSaleable()) : ?>
                <div class="flex flex-col-reverse items-center justify-between gap-1 sm:flex-row">
                    <?= $block->getChildHtml("product.info.quantity") ?>
                    <div class="w-full sm:w-auto 2xl:w-2/3" x-data="initComponent()" @private-content-loaded.window="receiveCustomerData($event.detail.data)">
        <template x-if="cart">
            <div class="w-full pr-2 mt-2 bg-white rounded-full xl:tracking-tighter 2xl:tracking-tight border-secondary">
                <div class="flex flex-row items-center justify-center sm:justify-start lg:text-base lg:text-left">
                
                    <span class="mr-1 text-base text-primary sm:text-lg md:text-base lg:text-sm xl:text-xs 2xl:text-sm"><?= $escaper->escapeHtml(__("Add ")) ?></span>
                    <span class="text-xl font-bold text-primary sm:text-xl md:text-lg lg:text-lg xl:text-base" x-text="hyva.formatPrice(buyMore)"></span>
                    <span class="ml-1 text-base sm:text-lg md:text-base lg:text-sm text-primary xl:text-xs 2xl:text-sm"><?= $escaper->escapeHtml(__(" for free shipping")) ?></span>
                </div>
            </div>
        </template>
        <template x-if="free">
            <div class="w-full p-2 mt-2 bg-green-400 rounded-lg 2xl:mt-0 xl:tracking-tighter 2xl:tracking-tight">
                <div class="font-bold text-white lg:text-base lg:text-left">
                    <span class="text-sm sm:text-lg lg:text-base"><?= $escaper->escapeHtml(__("Great! We'll ship it to you for free")) ?></span>
                </div>
            </div>
        </template>
    </div>
                </div>
                <?= $block->getChildHtml("product.info.addtocart") ?>
            <?php endif; ?>
        </div>

    </div>

    <?php if ($product->isSaleable()) : ?>
        <div class="flex justify-end mt-4">
            <?= $block->getChildHtml('addtocart.shortcut.buttons') ?>
        </div>
    <?php endif; ?>

    <div class="flex justify-end mt-4">
        <?= $block->getChildHtml('product.info.emailtofriend'); ?>
        <?= $block->getChildHtml('product.info.additional.actions'); ?>
    </div>

    <?php if ($tierPriceBlock = $block->getChildHtml("product.price.tier")) : ?>
        <div class="py-4 my-2 tier-price-container">
            <?=
            /** @noEscape */
            $tierPriceBlock ?>
        </div>
    <?php endif; ?>

    <?= $block->getChildHtml("product.info.additional") ?>
</div>

<script>
    "use strict";

    function initComponent() {
        return {
            cart: false,
            customer: false,
            free: false,
            receiveCustomerData(data) {

                if (data.cart.subtotalAmount === 0) {
                    this.cart = true;
                    this.buyMore = 49.90;
                    this.free = false;
                    return;
                }
                if (data.cart.subtotalAmount < 49.90) {
                    this.cart = true;
                    this.free = false;
                    this.buyMore = 49.90 - data.cart.subtotalAmount;
                    return;
                }

                if (data.cart.subtotalAmount >= 49.90) {
                    this.cart = false;
                    this.free = true;
                    return;
                }
            }
        }
    }
</script>