<?php

/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\CurrentProduct;
use Magento\Catalog\Model\Product;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Hyva\Theme\ViewModel\SvgIcons;


/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var SvgIcons $hyvaicons */
$hyvaicons = $viewModels->require(SvgIcons::class);

/** @var CurrentProduct $currentProduct */
$currentProduct = $viewModels->require(CurrentProduct::class);

/** @var Product $product */
$product = $this->hasData('product')
    ? $this->getData('product')
    : $currentProduct->get();

if (!$product || !$product->getId()) {
    return;
}
?>
<div class="flex justify-center w-1/2 h-10 xl:w-3/5">
    <?php if ($product->getIsSalable()) : ?>

        <div class="flex items-center justify-center w-full rounded-lg bg-verde">
            <span class="font-medium text-white"><?= $escaper->escapeHtmlAttr(__('available')) ?></span>
        </div>
        </p>
    <?php else : ?>
        <div class="ml-0.5 prodotto-non-disponibile">
            <?= $hyvaicons->checkredHtml('svg-stockstatus') ?>
            <span class="span-prodotto-non-disponibile"><?= $escaper->escapeHtmlAttr(__('Not available')) ?></span>
        </div>
    <?php endif; ?>
</div>