<?php

/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\CurrentProduct;
use Magento\Catalog\Model\Product;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Hyva\Theme\ViewModel\SvgIcons;


/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var SvgIcons $hyvaicons */
$hyvaicons = $viewModels->require(SvgIcons::class);

/** @var CurrentProduct $currentProduct */
$currentProduct = $viewModels->require(CurrentProduct::class);

/** @var Product $product */
$product = $this->hasData('product')
    ? $this->getData('product')
    : $currentProduct->get();

if (!$product || !$product->getId()) {
    return;
}
?>
<div class="">
    <?php if ($product->getIsSalable()) : ?>

        <div class="flex">
            <?= $hyvaicons->checkgreenHtml('w-6 h-6 ml-auto') ?>
            <span class="ml-2"><?= $escaper->escapeHtmlAttr(__('Product Available')) ?></span>
        </div>
        </p>
    <?php else : ?>
        <div class="flex">
            <?= $hyvaicons->checkredHtml('w-6 h-6 ml-auto') ?>
            <span class="ml-2"><?= $escaper->escapeHtmlAttr(__('Product not available')) ?></span>
        </div>
    <?php endif; ?>
</div>