<?php

/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;

/** @var Template $block */
/** @var Escaper $escaper */
?>
<div class="py-1 bg-secondary">
    <div class="container flex justify-center text-sm">
        <?= $block->escapeHtml(__('eCommerce Agency')) ?>
        <span>•</span>
        <a class="mx-1 hover:underline" href="https://www.armah.it/">armah.it</a>
        <span>•</span>
        <a class="ml-1 hover:underline" href="https://www.stefanoquitadamo.com/">stefanoquitadamo.com</a>
    </div>
</div>