<?php

/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Hyva\Theme\ViewModel\SvgIcons;
use Hyva\Theme\ViewModel\Wishlist;
use Magento\Wishlist\Helper\Data as WishlistHelper;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var ViewModelRegistry $viewModels */

/** @var SvgIcons $hyvaicons */
$hyvaicons = $viewModels->require(SvgIcons::class);

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

/** @var Hyva\Theme\ViewModel\StoreConfig $storeConfig */
$storeConfig = $viewModels->require(Hyva\Theme\ViewModel\StoreConfig::class);
$showMiniCart = $storeConfig->getStoreConfig(\Magento\Checkout\Block\Cart\Sidebar::XML_PATH_CHECKOUT_SIDEBAR_DISPLAY);
$wishlistViewModel = $viewModels->require(Wishlist::class);
$wishlistHelper = $this->helper(WishlistHelper::class);

?>
<script>
    function initHeader() {
        return {
            searchOpen: false,
            cart: {},
            scrolled: false,
            wishlistProducts: null,
            wishlistItemCount: 0,
            wishlistCountLabel: null,
            wishlistItems: {},
            getData(data) {
                if (data.cart) {
                    this.cart = data.cart
                }
                if (data.wishlist) {
                    this.wishlistProducts = data.wishlist;
                    this.wishlistCountLabel = '(' + this.wishlistProducts.counter + ')';
                    this.wishlistItemCount = this.wishlistProducts.items.length;
                    this.wishlistItems = this.wishlistProducts.items;
                }
            },
            handleScroll() {
                this.scrolled = window.scrollY > 10;
            }
        }
    }

    function initCompareHeader() {
        return {
            compareProducts: null,
            itemCount: 0,
            receiveCompareData(data) {
                if (data['compare-products']) {
                    this.compareProducts = data['compare-products'];
                    this.itemCount = this.compareProducts.count;
                }
            }
        }
    }
</script>
<div id="header" class="z-30 w-full border-b bg-primary" x-data="initHeader()" @keydown.window.escape="searchOpen = false;" @private-content-loaded.window="getData(event.detail.data)" @scroll.window="handleScroll">
    <div :class="{'py-1 sm:py-2': scrolled, 'py-1 md:pt-6 md:pb-5': !scrolled}" class="container flex flex-row items-center justify-between w-full px-6 mx-auto mt-0 duration-300 ease-in-out transition-padding">

        <!-- mobile -->
        <?= $block->getChildHtml("topmenu.mobile") ?>

        <div class="flex flex-row items-center justify-center lg:justify-between order-2 w-1/3 md:w-2/4 lg:order-1 lg:w-[30%] h-14">

            <!--Logo-->
            <div x-data="{ scrolled: false }" @scroll.window="scrolled = (window.pageYOffset > 0)" class="transition-transform duration-500 ease-in-out transform" :class="scrolled ? 'scale-125 sm:scale-125 md:scale-75' : 'scale-100 md:scale-90'">
                <?= $block->getChildHtml('logo'); ?>
            </div>
            <div class="hidden lg:hidden xl:block"><?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('header-numero-whatsapp')->toHtml(); ?></div>


        </div>

        <div class="relative flex-row items-start hidden xl:px-4 2xl:px-8 lg:order-2 lg:justify-center xl:justify-between lg:w-[40%] xl:w-2/5 2xl:w-5/12 lg:flex" id="search-content">


            <!--Search-->
            <div class="relative flex w-full">
                <?= $block->getChildHtml("header-search") ?>

            </div>

        </div>
        <div class="flex flex-row h-full items-center justify-end md:justify-end xl:justify-between order-3 w-1/3 lg:w-1/4 xl:w-[30%] xl:ml-2 2xl:ml-0">

            <div class="flex items-center justify-between w-full">

                <div class="flex flex-row items-center justify-end w-full gap-2 lg:gap-4 lg:items-end xl:gap-0 xl:items-center xl:justify-between">

                    <!-- header-blocco-spedizione-gratuita -->
                    <div class="hidden xl:block"><?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('header-blocco-spedizione-gratuita')->toHtml(); ?></div>

                    <!-- header-blocco-spedizione-gratuita -->
                    <div class="hidden xl:block"><?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('header-blocco-whatsapp')->toHtml(); ?></div>

                    <!--Search Icon-->
                    <div class="flex items-center mr-1 md:mr-0 lg:mr-2 lg:hidden lg:justify-start">
                        <button id="menu-search-icon" type="submit" title="<?= $escaper->escapeHtml(__("Search")) ?>" class="lg:hidden action search" aria-label="Search" @click.prevent=" searchOpen = !searchOpen; $nextTick(function () { document.querySelector('#search').select(); }); ">
                            <?= $heroicons->searchHtml('text-white border-current inline w-6 h-6'); ?>
                        </button>
                    </div>

                    <!--Customer Icon & Dropdown-->
                    <div class="flex flex-col items-center font-bold leading-5 text-white">
                        <a id="customer-menu" class="relative flex-col items-center hidden no-underline lg:flex" @click.prevent.stop="$dispatch('toggle-customer',{});" href="#">
                            <?= $hyvaicons->userHtml('text-primary lg:text-white border-current inline w-7 h-6'); ?>
                            <?= $escaper->escapeHtml(__('Login')); ?>
                        </a>

                    </div>
                    <!--Carrello-->
                    <div class="flex flex-col font-bold leading-5 text-white">

                        <a id="menu-cart-icon" <?php if ($showMiniCart) : ?>@click.prevent.stop="$dispatch('toggle-cart',{});" <?php endif ?> class="relative flex flex-col items-center justify-center no-underline" href="<?= $escaper->escapeUrl($block->getUrl('checkout/cart/index')) ?>">
                            <?= $hyvaicons->shopHtml('text-primary lg:text-white border-current inline w-5 h-7'); ?>

                            <span x-text="cart.summary_count" class="absolute flex items-center justify-center w-5 h-5 text-xs font-semibold leading-none text-center text-white uppercase transform -translate-x-5 translate-y-1/2 rounded-full -top-4 -right-8 lg:-right-3 sm:px-0 bg-giallo"></span>
                            <span class="hidden lg:block"><?= $escaper->escapeHtml(__('Cart')); ?></span>
                        </a>

                    </div>
                </div>
            </div>

        </div>
    </div>
    <!--Search-->
    <div class="absolute z-10 w-full bg-white border-t shadow-sm border-container-lighter" id="search-content" :class="{ 'block': searchOpen}" x-cloak x-show="searchOpen" @click.outside="searchOpen = false">
        <?= $block->getChildHtml('header-search'); ?>
    </div>

</div>

<!--Wishlist Drawer-->
<?= $block->getChildHtml("wishlist-drawer") ?>

<!--Customer Drawer-->
<?= $block->getChildHtml("customer-drawer") ?>

<!--Cart Drawer-->
<?= $block->getChildHtml("cart-drawer") ?>

<!--Authentication Pop-Up-->
<?= $block->getChildHtml("authentication-popup") ?>