<?php

/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Hyva\Theme\ViewModel\SvgIcons;
use Hyva\Theme\ViewModel\Wishlist;
use Magento\Wishlist\Helper\Data as WishlistHelper;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var ViewModelRegistry $viewModels */

/** @var SvgIcons $hyvaicons */
$hyvaicons = $viewModels->require(SvgIcons::class);

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

/** @var Hyva\Theme\ViewModel\StoreConfig $storeConfig */
$storeConfig = $viewModels->require(Hyva\Theme\ViewModel\StoreConfig::class);
$showMiniCart = $storeConfig->getStoreConfig(\Magento\Checkout\Block\Cart\Sidebar::XML_PATH_CHECKOUT_SIDEBAR_DISPLAY);
$wishlistViewModel = $viewModels->require(Wishlist::class);
$wishlistHelper = $this->helper(WishlistHelper::class);

?>
<script>
    function initHeader() {
        return {
            searchOpen: false,
            cart: {},
            scrolled: false,
            wishlistProducts: null,
            wishlistItemCount: 0,
            wishlistCountLabel: null,
            wishlistItems: {},
            getData(data) {
                if (data.cart) {
                    this.cart = data.cart
                }
                if (data.wishlist) {
                    this.wishlistProducts = data.wishlist;
                    this.wishlistCountLabel = '(' + this.wishlistProducts.counter + ')';
                    this.wishlistItemCount = this.wishlistProducts.items.length;
                    this.wishlistItems = this.wishlistProducts.items;
                }
            },
            handleScroll() {
                this.scrolled = window.scrollY > 10;
            }
        }
    }

    function initCompareHeader() {
        return {
            compareProducts: null,
            itemCount: 0,
            receiveCompareData(data) {
                if (data['compare-products']) {
                    this.compareProducts = data['compare-products'];
                    this.itemCount = this.compareProducts.count;
                }
            }
        }
    }
</script>
<div id="header" class="z-30 flex w-full h-12 border-t border-gray-100 bg-secondary" x-data="initHeader()" @keydown.window.escape="searchOpen = false;" @private-content-loaded.window="getData(event.detail.data)" @scroll.window="handleScroll">
    <div class="container flex flex-row items-center justify-between w-full px-6 mx-auto duration-300 ease-in-out transition-padding">

        <!-- mobile -->
        <?= $block->getChildHtml("topmenu.mobile") ?>

        <div class="flex flex-row items-center justify-start order-2 w-1/3 md:w-2/4 lg:order-1 lg:w-1/5 h-14">

    
            <?= $block->getChildHtml("primo.header.container.third") ?>

        </div>

        <div class="relative flex-row items-start hidden xl:px-4 2xl:px-8 lg:order-2 lg:justify-center xl:justify-between lg:w-[40%] xl:w-2/5 2xl:w-3/5 lg:flex" id="search-content">


            <!--Search-->
            <div class="relative flex w-full">
                <?= $block->getChildHtml("header-search") ?>

            </div>

        </div>
        <div class="flex flex-row items-center justify-end order-3 w-1/3 h-full md:justify-end xl:justify-between lg:w-1/4 xl:w-1/5 xl:ml-2 2xl:ml-0">

            <div class="flex items-center justify-between w-full">

                <div class="flex flex-row items-center justify-end w-full gap-2 lg:gap-4 lg:items-end xl:gap-4 xl:items-end xl:justify-end">

                    <!-- header-blocco-spedizione-gratuita -->
                    <div class="hidden xl:block"><?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('header-blocco-spedizione-gratuita')->toHtml(); ?></div>

                </div>
            </div>

        </div>
    </div>
    <!--Search-->
    <div class="absolute z-10 w-full border-t shadow-sm bg-secondary lg:bg-white border-container-lighter lg:hidden" id="search-content">
    <?= $block->getChildHtml('header-search'); ?>
</div>


</div>

<!--Wishlist Drawer-->
<?= $block->getChildHtml("wishlist-drawer") ?>

<!--Customer Drawer-->
<?= $block->getChildHtml("customer-drawer") ?>

<!--Cart Drawer-->
<?= $block->getChildHtml("cart-drawer") ?>

<!--Authentication Pop-Up-->
<?= $block->getChildHtml("authentication-popup") ?>