<?php

/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsSolid;
use Hyva\Theme\ViewModel\Navigation;
use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;
use Magento\Cms\Block\Block as CmsBlock;
use Hyva\Theme\ViewModel\SvgIcons;


/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

// phpcs:disable Generic.Files.LineLength.TooLong

/** @var SvgIcons $hyvaicons */
$hyvaicons = $viewModels->require(SvgIcons::class);

/** @var Navigation $viewModelNavigation */
$viewModelNavigation = $viewModels->require(Navigation::class);

/** @var HeroiconsSolid $heroiconsSolid */
$heroiconsSolid = $viewModels->require(HeroiconsSolid::class);

$uniqueId = '_' . uniqid();

// Order is important here: 1. build the menu data, 2. then set the cache tags from the view model identities
$menuItems = [[
    "id" => 0,
    "name" => "Categorie",
    "url" => "#",
    "childData" =>
    $viewModelNavigation->getNavigation(5)
]];
$block->setData('cache_tags', $viewModelNavigation->getIdentities());

?>
<div x-data="initMenuDesktop<?= $escaper->escapeHtml($uniqueId) ?>()" class="z-20 order-4 hidden w-full navigation lg:flex">
    <!-- desktop -->
    <div @load.window="setActiveMenu($root)" class="justify-between w-full mx-auto">
        <nav class="flex flex-wrap -mx-2">
            <?php foreach ($menuItems as $index => $itemLevel1) : ?>
                <?php $singleItems = []; ?>
                <div class="flex items-center px-2 mx-2 transition transition-colors duration-500 border-b-2 border-transparent level-0 group/parent xl:px-4 xl:mx-4 hover:border-primary focus-within:border-primary" @mouseover.stop="hoverTopPosition = $event.currentTarget.offsetTop + $event.currentTarget.getBoundingClientRect().height">
                <span class="items-center inline">
                            <?= $hyvaicons->Bars3BottomLeftHtml('w-8 h-8 inline text-primary', 25, 25) ?>
                        </span>
                    <a href="<?= $escaper->escapeUrl($itemLevel1['url']) ?>" @focus="hoverTopPosition = $event.currentTarget.parentNode.offsetTop + $event.currentTarget.parentNode.getBoundingClientRect().height" title="<?= $escaper->escapeHtmlAttr($itemLevel1['name']) ?>" class="block p-2 text-base text-primary level-0 whitespace-nowrap">
                        <?= $escaper->escapeHtml($itemLevel1['name']) ?>
                    </a>
                    <?php if (!empty($itemLevel1['childData'])) : ?>
                        
                        <div class="absolute left-0 z-10 w-full -mt-3 transition-opacity ease-out opacity-0 pointer-events-none top-full group-hover/parent:opacity-100 focus-within:opacity-100 group-hover/parent:pointer-events-auto" :style="`margin-top: 0; top: ${hoverTopPosition}px;`">
                            <div class="container relative pt-5 pb-64 mx-auto bg-white shadow-xl min-h-screen-50" :style="`min-height: ${menuMinHeight}px`">
                                <ul class="border-r-2 w-80 border-primary">
                                    <?php foreach ($itemLevel1['childData'] as $itemLevel2) : ?>


                                        <?php $singleItems = []; ?>
                                        <li class="flex items-center justify-between w-full group/child hover:bg-primary hover:text-white" <?php if (!empty($itemLevel2['childData'])) : ?> @mouseover.stop="setMenuMinHeight($event.currentTarget)" <?php endif; ?>>
                                            <a href="<?= $escaper->escapeUrl($itemLevel2['url']) ?>" class="relative z-10 w-full px-2 py-2 capitalize break-words" @focus="setMenuMinHeight($event.currentTarget.parentNode)">
                                                <?= strtolower($escaper->escapeHtml($itemLevel2['name'])) ?></a>

                                            </a>
                                            <?php if (!empty($itemLevel2['childData'])) : ?>
                                                <span class="relative z-10 inline-block px-2 py-2">
                                                    <?= $heroiconsSolid->chevronRightHtml('w-5 h-5 inline', 25, 25) ?>
                                                </span>
                                                <div class="container absolute top-0 left-0 w-full h-full opacity-0 pointer-events-none focus-within:opacity-100 group-hover/child:opacity-100 group-hover/child:pointer-events-auto">
                                                    <ul class="flex flex-row justify-between px-4 pt-10 pb-2">
                                                        <div class="grid w-3/4 grid-cols-3 ml-80 gap-y-4">
                                                            <?php foreach ($itemLevel2['childData'] as $itemLevel3) : ?>
                                                                <?php if (empty($itemLevel3['childData'])) : ?>
                                                                    <?php $singleItems[] = $itemLevel3 ?>
                                                                    <?php continue; ?>
                                                                <?php endif; ?>

                                                                <li class="level-1 min-w-48">
                                                                    <a href="<?= $escaper->escapeUrl($itemLevel3['url']) ?>" title="<?= $escaper->escapeHtmlAttr($itemLevel3['name']) ?>" class="block px-2 py-1 text-base font-medium leading-loose capitalize level-1 hover:underline text-primary">
                                                                        <?= strtolower($escaper->escapeHtml($itemLevel3['name'])) ?>

                                                                    </a>
                                                                    
                                                                    <ul class="z-10 w-full">
                                                                        <?php foreach ($itemLevel3['childData'] as $itemLevel4) : ?>
                                                                            <li class="level-2">
                                                                                <a href="<?= $escaper->escapeUrl($itemLevel4['url']) ?>" title="<?= $escaper->escapeHtmlAttr($itemLevel4['name']) ?>" class="block px-2 py-1 text-lg capitalize level-2 md:text-sm hover:underline text-primary"><?= strtolower($escaper->escapeHtml($itemLevel4['name'])) ?></a>

                                                                            </li>
                                                                        <?php endforeach; ?>
                                                                    </ul>

                                                                </li>

                                                            <?php endforeach; ?>
                                                        </div>



                                                        <?php if ($singleItems) : ?>
                                                            <li class="level-1 min-w-48">
                                                                <?php foreach ($singleItems as $item) : ?>
                                                                    <a href="<?= $escaper->escapeUrl($item['url']) ?>" title="<?= $escaper->escapeHtmlAttr($item['name']) ?>" class="block p-1 text-base font-semibold leading-loose capitalize level-1 hover:underline text-primary">
                                                                        <?= strtolower($escaper->escapeHtml($item['name'])) ?>

                                                                    </a>
                                                                <?php endforeach; ?>
                                                            <?php endif; ?>

                                                            <?php
                                                            $catIdLvl2    = ($pos = strrpos($itemLevel2['id'], 'category-node-')) !== false
                                                                ? substr($itemLevel2['id'], $pos + strlen('category-node-'))
                                                                : 0;

                                                            $cmsBlockHtml = $catIdLvl2
                                                                ? $this->getLayout()
                                                                ->createBlock(CmsBlock::class)
                                                                ->setBlockId('megamenu_block_right_cat' . $catIdLvl2)
                                                                ->toHtml()
                                                                : '';

                                                            if (!empty($cmsBlockHtml)) : ?>
                                                                <div class="max-w-xs 2xl:block">
                                                                    <?=
                                                                    /** @noEscape */
                                                                    $cmsBlockHtml ?>
                                                                </div>
                                                            <?php endif; ?>

                                                    </ul>
                                                </div>
                                            <?php endif ?>
                                        </li>
                                    <?php endforeach; ?>
                                </ul>
                            </div>
                        </div>
                    <?php endif; ?>
                </div>
            <?php endforeach; ?>

        </nav>
    </div>

</div>
<script>
    'use strict';

    const initMenuDesktop<?= $escaper->escapeHtml($uniqueId) ?> = () => {
        return {
            hoverTopPosition: '100%',
            menuMinHeight: 0,
            setMenuMinHeight(targetElement) {
                const childMenu = targetElement.querySelector('div.container.absolute');
                childMenu && (this.menuMinHeight = childMenu.getBoundingClientRect().height);
            },
            setActiveMenu(menuNode) {
                Array.from(menuNode.querySelectorAll('a')).filter(link => {
                    return link.href === window.location.href.split('?')[0];
                }).map(item => {
                    if (!item.classList.contains('level-0')) {
                        item.classList.add('underline');
                    }
                    item.closest('div.level-0') &&
                        item.closest('div.level-0').classList.add('border-secondary');
                });
            }
        }
    }
</script>