<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Shop By Hyva Compatibility
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Framework\Escaper;
use Amasty\Shopby\Block\Navigation\State;
use Amasty\ShopbyHyvaCompatibility\ViewModel\ProductListAjax;

/** @var Escaper $escaper */
/** @var State $block */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

/** @var ProductListAjax $productListAjax */
$productListAjax = $viewModels->require(ProductListAjax::class);

$filters = $block->getActiveFilters();
$value = [];
// phpcs:disable Generic.Files.LineLength.TooLong
?>

<?php if (!empty($filters)): ?>
    <div class="order-1 w-full p-4 bg-white border rounded mt-7 filter-current lg:px-8 lg:-mb-3" x-data="{ open: window.innerWidth > 1024 }">
        <div class="flex items-center justify-between cursor-pointer filter-options-title"
             @click="open = !open">
            <strong><?= $escaper->escapeHtml(__('Active filtering')) ?> <span class="inline-block lg:hidden">(<?= count($filters) ?>)</span></strong>
            <span class="px-1 py-1">
            <?= $heroicons->chevronDownHtml(
                'transition-transform transform duration-300 ease-in-out',
                24,
                24,
                [":class" => "{ 'rotate-180': open }"]
            ); ?>
        </span>
        </div>
        <div class="pt-1 pb-3 items am-filter" data-amshopby-filter-request-var="state" x-show="open">
            <?php foreach ($filters as $filter): ?>
                <?php
                $filterSetting = $block->getFilterSetting($filter->getFilter());

                /** @var \Magento\Catalog\Model\Layer\Filter\Item $filter */
                $value = $value ?: $filter->getValue();
                $resultValue = $block->getFilterValue($value, $filter);
                ?>
                <div class="amshopby-remove-item item flex justify-between items-center<?= /* @noEscape */ $filterSetting->isMultiselect() ? '' : ' radio-remove-item' ?>"
                    data-container="<?= /* @noEscape */ $filter->getFilter()->getRequestVar() ?>"
                    data-value="<?= /* @noEscape */ $block->getDataValue($resultValue) ?>"

                    <?php if (is_object($filter->getFilter()->getData('attribute_model')) && is_string($resultValue)): ?>
                        <?php $attributeId = $filter->getFilter()->getData('attribute_model')->getAttributeId() ?>
                        <?php $value = $productListAjax->getGroupsByAttributeId((int)$attributeId, $resultValue) ?>
                        data-attribute-id="<?= /* @noEscape */ $attributeId ?>"

                        <?php if ($value): ?>
                            data-massset="<?= $escaper->escapeJs($value) ?>"
                        <?php else: ?>
                            data-swatchset="<?= $escaper->escapeJs($resultValue) ?>"
                        <?php endif ?>
                    <?php endif ?>
                >
                    <span>
                        <span class="block capitalize filter-label"><?= strtolower($escaper->escapeHtml(__($filter->getName()))) ?></span>
                        <span class="block text-sm filter-value">
                            <?= $escaper->escapeHtml($block->stripTags($filter->getLabel())) ?>
                        </span>
                    </span>
                    <span>
                        <a class="block px-2 py-2 text-center amshopby-remove action remove text-primary hover:text-primary-darker"
                           href="<?= $escaper->escapeUrl($filter->getRemoveUrl()) ?>"
                           title="<?= /* @noEscape */ $escaper->escapeHtmlAttr(__('Remove This Item')) ?>"
                           @click.prevent.stop="window.dispatchEvent(new CustomEvent('amRemoveElement', {detail: {element: $event.currentTarget}}));">
                            <?= $heroicons->trashHtml('', 20, 20); ?>
                        </a>
                    </span>
                </div>
                <?php $value = $block->changeValueForMultiselect($filter->getFilter(), $value) ?>
            <?php endforeach; ?>

            <?php if ($block->getLayer()->getState()->getFilters()): ?>
                <div class="block-actions filter-actions">
                    <a href="<?= $escaper->escapeUrl($block->getClearUrl()) ?>"
                    class="text-sm text-primary hover:text-primary-darker"><?= $escaper->escapeHtml(__('Clear All')) ?></a>
                </div>
            <?php endif; ?>
            <div class="amshopby-button-wrap">
                <?php if ($block->getUnfoldedCount() && $block->getUnfoldedCount() < count($filters)): ?>
                    <?= /* @noEscape */ $block->createShowMoreButtonBlock() ?>
                <?php endif; ?>
            </div>
        </div>
    </div>
<?php endif; ?>
