<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);
?>

<div class="flex items-center justify-center flex-1 lg:p-4 carousel-nav product-carosello-nav">
    <button
        aria-label="<?= $escaper->escapeHtml(__('Previous')) ?>"
        class="hidden w-8 h-8 mr-1 text-black rounded-full outline-none glider-prev focus:outline-none product-left-carosello-nav">
        <?= $heroicons->chevronLeftHtml(); ?>
    </button>
    <div role="tablist" class="flex flex-wrap justify-center p-0 mx-1 select-none glider-dots focus:outline-none"></div>
    <button
        aria-label="<?= $escaper->escapeHtml(__('Next')) ?>"
        class="hidden w-8 h-8 text-black rounded-full outline-none glider-next focus:outline-none product-right-carosello-nav">
        <?= $heroicons->chevronRightHtml('svg-right-carosello-nav'); ?>
    </button>
</div>
