<?php

/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;

/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

?>
<script>
    function initMessages() {
        "use strict";
        return {
            messages: window.mageMessages || [],
            isEmpty() {
                return this.messages.reduce(
                    function(isEmpty, message) {
                        return isEmpty && message === undefined
                    }, true
                )
            },
            removeMessage(messageIndex) {
                this.messages[messageIndex].visible = false;
            },
            addMessages(messages, hideAfter = 5000) {
                messages.map((message) => {
                    message.visible = true;
                    this.messages = this.messages.concat(message);
                    this.setHideTimeOut(this.messages.length - 1, hideAfter);
                });
            },
            setHideTimeOut(messageIndex, hideAfter) {
                setTimeout(() => {
                    this.removeMessage(messageIndex);
                }, hideAfter);
            },
            eventListeners: {
                ['@messages-loaded.window']() {
                    this.addMessages(event.detail.messages, event.detail.hideAfter)
                },
                ['@private-content-loaded.window'](event) {
                    const data = event.detail.data;
                    if (
                        data.messages &&
                        data.messages.messages &&
                        data.messages.messages.length
                    ) {
                        this.addMessages(data.messages.messages);
                    }
                },
                ['@clear-messages.window']() {
                    this.messages = [];
                }
            }
        }
    }
</script>
<section id="messages" x-data="initMessages()" x-bind="eventListeners">
    <template x-if="!isEmpty()">
        <div class="w-full">
            <div role="alert" class="container fixed py-3 mx-auto messages top-40 w-fit">
                <template x-for="(message, index) in messages" :key="index">
                    <div x-show="message.visible" x-transition:enter="transition ease-out duration-300" x-transition:enter-start="opacity-0 transform scale-90" x-transition:enter-end="opacity-100 transform scale-100" x-transition:leave="transition ease-in duration-300" x-transition:leave-start="opacity-100 transform scale-100" x-transition:leave-end="opacity-0 transform scale-90">
                        <div class="gap-8 h-fit rounded-xl message" :class="message.type" :ui-id="'message-' + message.type">
                            <span x-html="message.text"></span>
                            <a href="#" class="cursor-pointer close" title="close" @click.prevent="removeMessage(index)">
                                <?= $heroicons->XCircleHtml('text-white w-7 h-7', 18, 18); ?>
                            </a>
                        </div>
                    </div>
                </template>
            </div>
        </div>
    </template>
</section>